version: "3"
services:

    api:
        build: ./dotnetcore-api
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        build:
            context: ./
            dockerfile: ./mssql-db/docker/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "1433:1433"
        container_name: db