version: "3"
services:
    db1:
        build:
            context: ./
            dockerfile: ./mssql-db/db1/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "2500:1433"
        container_name: db1
    db2:
        build:
            context: ./
            dockerfile: ./mssql-db/db2/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "2600:1433"
        container_name: db2
    db3:
        build:
            context: ./
            dockerfile: ./mssql-db/db3/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "2700:1433"
        container_name: db3

    webapp:
            build: ./webapp
            ports:
                - "8080:8080"
            depends_on:
                - db1