version: "3"
services:
    webapp:
        build: ./dotnetcore-api
        ports:
            - "5000:5000"
        depends_on:
            - db
    db1:
        build:
            context: ./
            dockerfile: ./mssql-db/db1/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "2500:1433"
        container_name: db1
    db2:
        build:
            context: ./
            dockerfile: ./mssql-db/db2/Dockerfile
            args:
                DBNAME : ${DBNAME}
                PASSWORD : ${PASSWORD}
                MPID : ${MPID}
        ports:
            - "2600:1433"
        container_name: db2