name: Pitchoun API build

on:
  push:
    paths:
    - 'dotnetcore-api/ClientApi**'
    branches: [ master ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: master

    - name: Run unit tests
      run: dotnet test unit-tests/ClientApi/*.csproj
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path: .
        dockerfile: './dotnetcore-api/ClientApi/Dockerfile'
        repository: 'client.api'
        tags: 'linux-latest'
        push: true