name: Client API deploy

on:
  push:
    paths:
    - 'k8s/ClientApi/**'
    branches: [ master ]

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    env:
      ENV: dev
      LOCATION: westeurope
    steps:
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: 'wksdevopsql-${{ env.ENV }}-rg'
        cluster-name: 'wksdevopsql-${{ env.ENV }}-aks'

    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: main

    - name: Helm tool installer
      uses: Azure/setup-helm@v1

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy
      run: >
        helm upgrade 
        --install wksdevopsql-clientapi
        --namespace=default 
        --set registry=${{ secrets.REGISTRY_LOGIN_SERVER }} 
        --set imagePullPolicy=Always 
        --set host=${{ secrets.IP_ADDRESS }} 
        --set protocol=http './k8s-cluster/ClientApi-helm'