version: '3.2'



services:

  db:
    
    image: microsoft/nanoserver:latest
    
    command: "ping 8.8.8.8"

    ports:

      - "8000:8000"



networks:

  default:

    external:

      name: nat