# This is a basic workflow that is manually triggered

name: CD_prd_sql_manu_workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

  workflow_run:
    workflows: ["CD_stg_sql_auto_workflow"]
    branches: [master]
    types: 
      - completed

jobs:
  # This workflow contains a twos job called "sql-build" & "sql-deploy"
  sql-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ENV: prd
      LOCATION: westeurope
      EDITION: standard

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: CLI Creating Resource Group
        run: |
          az group create -l westeurope -n wks-devopsql-${{ env.ENV }}-rg

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: 1619bfac-1484-4da0-95cc-dec25338e962
          resourceGroupName: wks-devopsql-${{ env.ENV }}-rg
          template: wks-devops_az_sql/mssql-db/arm/azuredeploy.json
          parameters: 'serverName="wksdevopsql-sql-${{ env.ENV }}" sqlDBName="wksdevopsql-db-${{ env.ENV }}" location="${{ env.LOCATION }}" administratorLogin=${{ secrets.SQL_SA_USER }} administratorLoginPassword=${{ secrets.SQL_SA_PASSWORD }} databaseEdition="${{ env.EDITION }}" env="${{ env.ENV }}"'
      
